Add volume adjustment for chat beeps
yvt/openspades pull request #952
Opened 2021-05-05 07:46 UTC by Pablo-Dallegri

2021-05-05 09:19 UTC, yvt requested changes

2021-05-05 09:19 UTC, yvt commented on Sources/Client/Client.cpp
> +DEFINE_SPADES_SETTING(cg_chatBeep, "100");
The existing users will keep using the old value of `cg_chatBeep`, so changing the value range or the default value is not recommended. I suggest using a 0–1 range (with intermediate values).

2021-05-05 09:19 UTC, yvt commented on Sources/Client/Client.cpp
> +				params.volume = (int)cg_chatBeep / 100.f;
You can cast it to `float`.

2021-05-05 09:19 UTC, yvt commented on Resources/Scripts/Gui/Preferences.as
> +                                    0, 100, 1, ConfigNumberFormatter(0, "%"));
Add a new constructor overload to `ConfigNumberFormatter` to take a new parameter `prescale`. Use it to rescale the displayed value to a 0–100% range.

2021-05-05 13:02 UTC, NotAFile commented
Might it be better to have a general "ui" volume slider that applies to all such effects?

2021-05-06 12:34 UTC, yvt approved these changes

2021-05-06 12:34 UTC, merged

2021-05-06 12:34 UTC, yvt commented
Looks good, thanks!